name: 'Publish pre-release'
on:
  pull_request:

jobs:
  create-files-and-upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Create directory publish_workflow_payload
        run: |
          mkdir -p publish_workflow_payload

      - name: Prepare payload data
        run: |
          mkdir -p publish_workflow_payload
          echo "testvers" > publish_workflow_payload/next_version.txt
          echo "@vkontakte/vkui" > publish_workflow_payload/package_name.txt
          echo "testtag" > publish_workflow_payload/npm_tag.txt
          echo "testrealesetag" > publish_workflow_payload/git_release_tag.txt
          echo "testmilestone" > publish_workflow_payload/close_milestone.txt
        shell: bash

      - name: Upload payload data to artifact for deploy workflow
        uses: actions/upload-artifact@v4
        with:
          name: publish_workflow_payload
          path: publish_workflow_payload
          retention-days: 1
