name: 'Publish pre-release'
on:
  workflow_dispatch:

jobs:
  create-files-and-upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Create directory publish_workflow_payload
        run: |
          mkdir -p publish_workflow_payload

      - name: Create package-name.txt and next-version.txt
        run: |
          echo "@vkontakte/vkui" > publish_workflow_payload/package-name.txt
          echo "testnextversion" > publish_workflow_payload/next-version.txt

      - name: Verify files exist
        run: |
          ls -la publish_workflow_payload/
          cat publish_workflow_payload/package-name.txt
          cat publish_workflow_payload/next-version.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish_workflow_payload
          path: publish_workflow_payload/
